No configuration file found.
No pyproject.toml file found.
stubPath /mnt/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorflow_tfx/5a48f0c232acef1a9e21a68ba1b047fdc4d4444a/typings is not a valid directory.
Assuming Python platform Linux
Searching for source files
Found 3 source files
/home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorflow_tfx/5a48f0c232acef1a9e21a68ba1b047fdc4d4444a/a/tfx/orchestration/test_utils.py
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorflow_tfx/5a48f0c232acef1a9e21a68ba1b047fdc4d4444a/a/tfx/orchestration/test_utils.py:23:8 - error: Import "docker" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorflow_tfx/5a48f0c232acef1a9e21a68ba1b047fdc4d4444a/a/tfx/orchestration/test_utils.py:25:6 - error: Import "google.cloud" could not be resolved (reportMissingImports)
/home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorflow_tfx/5a48f0c232acef1a9e21a68ba1b047fdc4d4444a/a/tfx/orchestration/kubeflow/kubeflow_e2e_test.py
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorflow_tfx/5a48f0c232acef1a9e21a68ba1b047fdc4d4444a/a/tfx/orchestration/kubeflow/kubeflow_e2e_test.py:29:6 - error: Import "tfx.orchestration" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorflow_tfx/5a48f0c232acef1a9e21a68ba1b047fdc4d4444a/a/tfx/orchestration/kubeflow/kubeflow_e2e_test.py:30:6 - error: Import "tfx.orchestration" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorflow_tfx/5a48f0c232acef1a9e21a68ba1b047fdc4d4444a/a/tfx/orchestration/kubeflow/kubeflow_e2e_test.py:31:6 - error: Import "tfx.orchestration.kubeflow" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorflow_tfx/5a48f0c232acef1a9e21a68ba1b047fdc4d4444a/a/tfx/orchestration/kubeflow/kubeflow_e2e_test.py:32:6 - error: Import "tfx.orchestration.test_pipelines" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorflow_tfx/5a48f0c232acef1a9e21a68ba1b047fdc4d4444a/a/tfx/orchestration/kubeflow/kubeflow_e2e_test.py:33:6 - error: Import "tfx.types" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorflow_tfx/5a48f0c232acef1a9e21a68ba1b047fdc4d4444a/a/tfx/orchestration/kubeflow/kubeflow_e2e_test.py:35:6 - error: Import "ml_metadata.proto" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorflow_tfx/5a48f0c232acef1a9e21a68ba1b047fdc4d4444a/a/tfx/orchestration/kubeflow/kubeflow_e2e_test.py:36:6 - error: Import "ml_metadata.proto" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorflow_tfx/5a48f0c232acef1a9e21a68ba1b047fdc4d4444a/a/tfx/orchestration/kubeflow/kubeflow_e2e_test.py:37:6 - error: Import "ml_metadata.proto" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorflow_tfx/5a48f0c232acef1a9e21a68ba1b047fdc4d4444a/a/tfx/orchestration/kubeflow/kubeflow_e2e_test.py:128:12 - error: "proc" is possibly unbound (reportUnboundVariable)
/home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorflow_tfx/5a48f0c232acef1a9e21a68ba1b047fdc4d4444a/a/tfx/tools/cli/e2e/cli_kubeflow_e2e_test.py
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorflow_tfx/5a48f0c232acef1a9e21a68ba1b047fdc4d4444a/a/tfx/tools/cli/e2e/cli_kubeflow_e2e_test.py:35:8 - error: Import "kfp" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorflow_tfx/5a48f0c232acef1a9e21a68ba1b047fdc4d4444a/a/tfx/tools/cli/e2e/cli_kubeflow_e2e_test.py:36:8 - error: Import "kfp_server_api" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorflow_tfx/5a48f0c232acef1a9e21a68ba1b047fdc4d4444a/a/tfx/tools/cli/e2e/cli_kubeflow_e2e_test.py:39:6 - error: Import "google.cloud" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorflow_tfx/5a48f0c232acef1a9e21a68ba1b047fdc4d4444a/a/tfx/tools/cli/e2e/cli_kubeflow_e2e_test.py:40:6 - error: Import "tfx.tools.cli" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorflow_tfx/5a48f0c232acef1a9e21a68ba1b047fdc4d4444a/a/tfx/tools/cli/e2e/cli_kubeflow_e2e_test.py:41:6 - error: Import "tfx.tools.cli.cli_main" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorflow_tfx/5a48f0c232acef1a9e21a68ba1b047fdc4d4444a/a/tfx/tools/cli/e2e/cli_kubeflow_e2e_test.py:42:6 - error: Import "tfx.tools.cli.e2e" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorflow_tfx/5a48f0c232acef1a9e21a68ba1b047fdc4d4444a/a/tfx/tools/cli/e2e/cli_kubeflow_e2e_test.py:48:20 - error: Cannot access member "decode" for type "Text"
    Member "decode" is unknown (reportGeneralTypeIssues)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorflow_tfx/5a48f0c232acef1a9e21a68ba1b047fdc4d4444a/a/tfx/tools/cli/e2e/cli_kubeflow_e2e_test.py:47:44 - error: Function with declared type of "Text" must return value
    Type "None" cannot be assigned to type "Text" (reportGeneralTypeIssues)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorflow_tfx/5a48f0c232acef1a9e21a68ba1b047fdc4d4444a/a/tfx/tools/cli/e2e/cli_kubeflow_e2e_test.py:105:9 - error: Argument of type "bytes" cannot be assigned to parameter "config" of type "Text" in function "_get_endpoint"
    "bytes" is incompatible with "Text" (reportGeneralTypeIssues)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorflow_tfx/5a48f0c232acef1a9e21a68ba1b047fdc4d4444a/a/tfx/tools/cli/e2e/cli_kubeflow_e2e_test.py:431:25 - error: "id" is not a known member of "None" (reportOptionalMemberAccess)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorflow_tfx/5a48f0c232acef1a9e21a68ba1b047fdc4d4444a/a/tfx/tools/cli/e2e/cli_kubeflow_e2e_test.py:446:41 - error: "id" is not a known member of "None" (reportOptionalMemberAccess)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorflow_tfx/5a48f0c232acef1a9e21a68ba1b047fdc4d4444a/a/tfx/tools/cli/e2e/cli_kubeflow_e2e_test.py:461:76 - error: "id" is not a known member of "None" (reportOptionalMemberAccess)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorflow_tfx/5a48f0c232acef1a9e21a68ba1b047fdc4d4444a/a/tfx/tools/cli/e2e/cli_kubeflow_e2e_test.py:464:27 - error: "id" is not a known member of "None" (reportOptionalMemberAccess)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorflow_tfx/5a48f0c232acef1a9e21a68ba1b047fdc4d4444a/a/tfx/tools/cli/e2e/cli_kubeflow_e2e_test.py:483:29 - error: "id" is not a known member of "None" (reportOptionalMemberAccess)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/tensorflow_tfx/5a48f0c232acef1a9e21a68ba1b047fdc4d4444a/a/tfx/tools/cli/e2e/cli_kubeflow_e2e_test.py:484:29 - error: "id" is not a known member of "None" (reportOptionalMemberAccess)
26 errors, 0 warnings, 0 infos 
Completed in 2.431sec

time cost(in seconds): 2.6782491207122803
