No configuration file found.
No pyproject.toml file found.
stubPath /mnt/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/typings is not a valid directory.
Assuming Python platform Linux
Searching for source files
Found 1 source file
/home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/a/hub/api/dataset.py
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/a/hub/api/dataset.py:9:8 - error: Import "fsspec" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/a/hub/api/dataset.py:10:8 - error: Import "numcodecs" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/a/hub/api/dataset.py:11:8 - error: Import "numcodecs.lz4" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/a/hub/api/dataset.py:12:8 - error: Import "numcodecs.zstd" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/a/hub/api/dataset.py:14:6 - error: Import "hub.schema.features" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/a/hub/api/dataset.py:21:6 - error: Import "hub.log" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/a/hub/api/dataset.py:25:6 - error: Import "hub.api.objectview" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/a/hub/api/dataset.py:26:6 - error: Import "hub.api.tensorview" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/a/hub/api/dataset.py:27:6 - error: Import "hub.api.dataset_utils" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/a/hub/api/dataset.py:34:8 - error: Import "hub.schema.serialize" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/a/hub/api/dataset.py:35:8 - error: Import "hub.schema.deserialize" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/a/hub/api/dataset.py:36:6 - error: Import "hub.schema.features" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/a/hub/api/dataset.py:38:6 - error: Import "hub.store.dynamic_tensor" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/a/hub/api/dataset.py:39:6 - error: Import "hub.store.store" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/a/hub/api/dataset.py:40:6 - error: Import "hub.exceptions" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/a/hub/api/dataset.py:51:6 - error: Import "hub.store.metastore" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/a/hub/api/dataset.py:52:6 - error: Import "hub.client.hub_control" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/a/hub/api/dataset.py:53:6 - error: Import "hub.schema" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/a/hub/api/dataset.py:54:6 - error: Import "hub.numcodecs" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/a/hub/api/dataset.py:56:6 - error: Import "hub.utils" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/a/hub/api/dataset.py:57:6 - error: Import "hub" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/a/hub/api/dataset.py:520:16 - error: Import "torch" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/a/hub/api/dataset.py:522:16 - error: "torch" is assigned before global declaration
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/a/hub/api/dataset.py:549:20 - error: "tf" is assigned before global declaration
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/a/hub/api/dataset.py:745:20 - error: "tf" is assigned before global declaration
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/a/hub/api/dataset.py:829:20 - error: Import "tensorflow_datasets" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/a/hub/api/dataset.py:831:20 - error: "tfds" is assigned before global declaration
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/a/hub/api/dataset.py:1020:20 - error: Import "torch" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/a/hub/api/dataset.py:1022:20 - error: "torch" is assigned before global declaration
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/a/hub/api/dataset.py:749:59 - error: "dict_" is not a known member of "None" (reportOptionalMemberAccess)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/a/hub/api/dataset.py:750:45 - error: "dict_" is not a known member of "None" (reportOptionalMemberAccess)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/a/hub/api/dataset.py:867:54 - error: No overloads for "__new__" match the provided arguments
    Argument types: (None, Unknown) (reportGeneralTypeIssues)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/a/hub/api/dataset.py:866:25 - error: Argument of type "tuple[Unknown, ...]" cannot be assigned to parameter "v" of type "None" in function "__setitem__"
    Type cannot be assigned to type "None" (reportGeneralTypeIssues)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/a/hub/api/dataset.py:871:25 - error: Argument of type "tuple[int]" cannot be assigned to parameter "v" of type "None" in function "__setitem__"
    Type cannot be assigned to type "None" (reportGeneralTypeIssues)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/a/hub/api/dataset.py:873:46 - error: No overloads for "max" match the provided arguments
    Argument types: (tuple[tuple[int], None]) (reportGeneralTypeIssues)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/a/hub/api/dataset.py:882:38 - error: "dict_" is not a known member of "None" (reportOptionalMemberAccess)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/a/hub/api/dataset.py:1038:25 - error: Argument of type "tuple[int]" cannot be assigned to parameter "v" of type "None" in function "__setitem__"
    Type cannot be assigned to type "None" (reportGeneralTypeIssues)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/a/hub/api/dataset.py:1040:46 - error: No overloads for "max" match the provided arguments
    Argument types: (tuple[int], None) (reportGeneralTypeIssues)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/a/hub/api/dataset.py:1046:54 - error: No overloads for "__new__" match the provided arguments
    Argument types: (None, Unknown) (reportGeneralTypeIssues)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/a/hub/api/dataset.py:1045:25 - error: Argument of type "tuple[Unknown, ...]" cannot be assigned to parameter "v" of type "None" in function "__setitem__"
    Type cannot be assigned to type "None" (reportGeneralTypeIssues)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/a/hub/api/dataset.py:1072:31 - error: Cannot access member "dtype" for type "str"
    Member "dtype" is unknown (reportGeneralTypeIssues)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/a/hub/api/dataset.py:1128:79 - error: "shape" is not a known member of "None" (reportOptionalMemberAccess)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/a/hub/api/dataset.py:1134:29 - error: "_tensors" is not a known member of "None" (reportOptionalMemberAccess)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/a/hub/api/dataset.py:1141:40 - error: "_tensors" is not a known member of "None" (reportOptionalMemberAccess)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/a/hub/api/dataset.py:1142:26 - error: "_tensors" is not a known member of "None" (reportOptionalMemberAccess)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/a/hub/api/dataset.py:1144:30 - error: "_tensors" is not a known member of "None" (reportOptionalMemberAccess)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/a/hub/api/dataset.py:1146:25 - error: "torch" is not defined (reportUndefinedVariable)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/activeloopai_Hub/c23c1d94b490dd1f9fc0c08838801c3666e7bc4c/a/hub/api/dataset.py:70:9 - error: Parameter declaration "schema" is obscured by a declaration of the same name (reportGeneralTypeIssues)
48 errors, 0 warnings, 0 infos 
Completed in 1.998sec

time cost(in seconds): 2.1688365936279297
