No configuration file found.
No pyproject.toml file found.
stubPath /mnt/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/thu-ml_zhusuan/35f3db2fb3a57545d89ea335dd880cb189451b27/typings is not a valid directory.
Assuming Python platform Linux
Searching for source files
Found 1 source file
/home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/thu-ml_zhusuan/35f3db2fb3a57545d89ea335dd880cb189451b27/a/examples/utils/dataset.py
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/thu-ml_zhusuan/35f3db2fb3a57545d89ea335dd880cb189451b27/a/examples/utils/dataset.py:12:6 - warning: Import "six.moves" could not be resolved from source (reportMissingModuleSource)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/thu-ml_zhusuan/35f3db2fb3a57545d89ea335dd880cb189451b27/a/examples/utils/dataset.py:13:6 - warning: Import "six.moves" could not be resolved from source (reportMissingModuleSource)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/thu-ml_zhusuan/35f3db2fb3a57545d89ea335dd880cb189451b27/a/examples/utils/dataset.py:73:50 - error: Argument of type "GzipFile" cannot be assigned to parameter "file" of type "IO[bytes]" in function "load"
    "GzipFile" is incompatible with "IO[bytes]" (reportGeneralTypeIssues)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/thu-ml_zhusuan/35f3db2fb3a57545d89ea335dd880cb189451b27/a/examples/utils/dataset.py:176:32 - error: Argument of type "TextIOWrapper" cannot be assigned to parameter "file" of type "IO[bytes]" in function "load"
    TypeVar "AnyStr@IO" is invariant
      "str" is incompatible with "bytes" (reportGeneralTypeIssues)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/thu-ml_zhusuan/35f3db2fb3a57545d89ea335dd880cb189451b27/a/examples/utils/dataset.py:184:28 - error: Argument of type "TextIOWrapper" cannot be assigned to parameter "file" of type "IO[bytes]" in function "load"
    TypeVar "AnyStr@IO" is invariant
      "str" is incompatible with "bytes" (reportGeneralTypeIssues)
3 errors, 2 warnings, 0 infos 
Completed in 1.816sec

time cost(in seconds): 1.983912467956543
